on: [push]

name: CI

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: cargo -vv build --release
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release
  docs:
    name: Publish docs
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Generate docs
        uses: actions-rs/cargo@v1
        with:
          command: docs
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/doc
